### ISSUE TITLE
Deploying on own server

### ISSUE THREAD

**Issue by xaviablaza** [ManuelB/BusinessCardCRM#1]
Hi Manuel, is there any documentation available on how to replicate this on my own system? I've tried running your gruntfile locally and I seem to be getting some strange errors when loading the site.

**Comment by ManuelB** [comment]
@xaviablaza the Gruntfile is not required I think it was auto generate by SAP webide. Just put the whole files in any webserver and open it in a browser e.g.

```
git clone https://github.com/ManuelB/BusinessCardCRM.git
cd BusinessCardCRM
python -m SimpleHTTPServer 8000
# open http://localhost:8000/webapp/ in a browser
/opt/google/chrome/chrome http://localhost:8000/webapp/
```

A working version can be found here:
https://manuelb.github.io/BusinessCardCRM/webapp/

You can find a video where I talk about the system here:
https://www.youtube.com/watch?v=uGNgCvesazQ

And I will be giving a talk on the UI5Con:
http://openui5.org/ui5con/#section-lineup

Hope that helps.

There is no documentation available how to get all the keys from Google Cloud Platform etc. if you need support you can hire me :-)

http://www.incentergy.de/impressum/kontakt/
